# Generated by Django 4.2.23 on 2025-09-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='image_url',
        ),
        migrations.AddField(
            model_name='entity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='entities/'),
        ),
    ]
