# Generated by Django 4.2.23 on 2025-10-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_remove_entity_image_url_entity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
